//! Embedded tcp-ip management ELF binaries.
//!
//! Generated by build.rs from third_party/tcp-ip.
//! Each constant is either the full ELF bytes (when the submodule built
//! successfully) or an empty slice (when the submodule was unavailable).
//! Call [`install`] after VFS initialisation to expose the binaries under
//! `/bin/`.

include!(concat!(env!("OUT_DIR"), "/net_bins.rs"));

/// Write the embedded ELF binaries to `/bin/` in the global VFS.
///
/// No-ops for any binary whose embedded slice is empty (submodule not built).
pub fn install() {
    use crate::vfs::{VFS, VfsError};

    let bins: &[(&str, &[u8])] = &[
        ("/bin/wifi", WIFI_ELF),
        ("/bin/ping", PING_ELF),
        ("/bin/ifconfig", IFCONFIG_ELF),
        ("/bin/netstat", NETSTAT_ELF),
    ];

    // Check whether any binaries are actually embedded before touching the VFS.
    if bins.iter().all(|(_, data)| data.is_empty()) {
        return;
    }

    let mut lock = VFS.lock();
    let Some(vfs) = lock.as_mut() else { return };

    // Ensure /bin exists in the underlying root filesystem so write_file works.
    match vfs.mkdir("/bin") {
        Ok(()) | Err(VfsError::AlreadyExists) => {}
        Err(e) => {
            crate::serial_println!("[net_bins] failed to create /bin: {}", e);
            return;
        }
    }

    for (path, data) in bins {
        if data.is_empty() {
            continue;
        }
        if let Err(e) = vfs.write_file(path, data) {
            crate::serial_println!("[net_bins] failed to install {}: {}", path, e);
        } else {
            crate::serial_println!("[net_bins] installed {} ({} bytes)", path, data.len());
        }
    }
}
